// <auto-generated />
namespace BookReviewService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Book_User_Tbl_Validations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Book_User_Tbl_Validations));
        
        string IMigrationMetadata.Id
        {
            get { return "202003301736242_Book_User_Tbl_Validations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
